name: Deploy

on:
  workflow_call:

jobs:
  Site:
    runs-on: ubuntu-latest
    steps:
      - name: Curl test...
        run: |
          curl \
            -H "Content-Type: application/json" \
            -H "CG-Organization: $ORGANIZATION_ID" \
            -H "CG-Instance: $SITE_ID" \
            -H "X-PAT: $WEBHOOK_TOKEN" \
            -d '{ "data": { "status": "clone" } }' \
            -X POST "$WEBHOOK_STATUS_URL"
        env:
          ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
          SITE_ID: ${{ secrets.SITE_ID }}
          WEBHOOK_STATUS_URL: ${{ secrets.WEBHOOK_STATUS_URL }}
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v2.1.2
        with:
          args: projects:list
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
