name: Deploy Site

on:
  workflow_call:

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout: repository"
        uses: actions/checkout@v3
          
      - name: "Checkout: coldandgoji/actions"
        uses: actions/checkout@v3
        with:
          path: ./.github/actions
          repository: coldandgoji/actions
          token: ${{ secrets.WEBHOOK_TOKEN }}

      - name: "Status: Prepare"
        uses: ./.github/actions/site-update-status
        with:
          BUILD_STATUS: prepare
          ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
          SITE_ID: ${{ secrets.SITE_ID }}
          WEBHOOK_STATUS_URL: ${{ secrets.WEBHOOK_STATUS_URL }}
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}

      - name: "Install Dependencies"
        uses: ./.github/actions/site-install-dependencies
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Status: Build"
        uses: ./.github/actions/site-update-status
        with:
          BUILD_STATUS: build
          ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
          SITE_ID: ${{ secrets.SITE_ID }}
          WEBHOOK_STATUS_URL: ${{ secrets.WEBHOOK_STATUS_URL }}
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}

      - name: "Build: Site"
        uses: ./.github/actions/site-build

      - name: "Status: Deploy"
        uses: ./.github/actions/site-update-status
        with:
          BUILD_STATUS: deploy
          ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
          SITE_ID: ${{ secrets.SITE_ID }}
          WEBHOOK_STATUS_URL: ${{ secrets.WEBHOOK_STATUS_URL }}
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}

      - name: "Deploy: Site"
        uses: ./.github/actions/site-deploy
        with:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: "Status: Complete"
        uses: ./.github/actions/site-update-status
        with:
          BUILD_STATUS: complete
          ORGANIZATION_ID: ${{ secrets.ORGANIZATION_ID }}
          SITE_ID: ${{ secrets.SITE_ID }}
          WEBHOOK_STATUS_URL: ${{ secrets.WEBHOOK_STATUS_URL }}
          WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
